// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("AssessmentSchema")
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.AccountHolder", b =>
                {
                    b.Property<long>("IdNumber")
                        .HasMaxLength(13)
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Dob")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(55)
                        .HasColumnType("nvarchar(55)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(55)
                        .HasColumnType("nvarchar(55)");

                    b.Property<long>("MobileNumber")
                        .HasMaxLength(10)
                        .HasColumnType("bigint");

                    b.Property<string>("ResidentialAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdNumber");

                    b.HasIndex("IdNumber");

                    b.ToTable("AccountHolders", "AssessmentSchema");
                });

            modelBuilder.Entity("Domain.Entities.AuditTrail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Changes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<long>("UserId")
                        .HasMaxLength(13)
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.ToTable("AuditTrails", "AssessmentSchema");
                });

            modelBuilder.Entity("Domain.Entities.BankAccount", b =>
                {
                    b.Property<long>("AccountNumber")
                        .HasMaxLength(25)
                        .HasColumnType("bigint");

                    b.Property<long>("AccountHolderId")
                        .HasMaxLength(13)
                        .HasColumnType("bigint");

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("AccountStatus")
                        .HasColumnType("bit");

                    b.Property<int>("AccountType")
                        .HasMaxLength(55)
                        .HasColumnType("int");

                    b.Property<long>("AvailableBalance")
                        .HasPrecision(2147483647, 2)
                        .HasColumnType("bigint");

                    b.HasKey("AccountNumber");

                    b.HasIndex("AccountHolderId");

                    b.HasIndex("AccountNumber");

                    b.ToTable("BankAccounts", "AssessmentSchema");
                });

            modelBuilder.Entity("Domain.Entities.Withdrawal.Withdrawal", b =>
                {
                    b.Property<Guid>("WithdrawalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("AccountNumber")
                        .HasMaxLength(25)
                        .HasColumnType("bigint");

                    b.Property<int>("AccountType")
                        .HasMaxLength(55)
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<long>("WithdrawalAmount")
                        .HasColumnType("bigint");

                    b.HasKey("WithdrawalId");

                    b.HasIndex("WithdrawalId");

                    b.ToTable("Withdrawals", "AssessmentSchema");
                });
#pragma warning restore 612, 618
        }
    }
}
